name: Deploy

on:
  push:
    # branches:
    #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      # リポジトリのソースコードを取得
      - name: Checkout code
        uses: actions/checkout@v4

      # RubyとBundlerをセットアップし、依存関係をキャッシュ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Docker Buildxをセットアップしてビルドキャッシュを有効化
      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      # GitHubランタイム情報をExposeしてDockerキャッシュを最適化
      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      # AWSの認証情報を設定（ECRやEC2にアクセスするため）
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # EC2へのSSH接続を有効化（Kamalがデプロイできるように）
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # RailsのRAILS_MASTER_KEYをKamal用に.secretsファイルへ出力
      - name: Create secrets file
        run: |
          mkdir -p .kamal
          echo "RAILS_MASTER_KEY=$RAILS_MASTER_KEY" > .kamal/secrets

      # デバッグ: 環境変数とKamal設定の確認
      - name: Debug Kamal configuration
        run: |
          echo "=== Environment check ==="
          echo "RAILS_MASTER_KEY is set: ${RAILS_MASTER_KEY:+yes}"
          echo "RAILS_MASTER_KEY length: ${#RAILS_MASTER_KEY}"
          
          echo "=== File system check ==="
          echo "Secrets file exists: $(test -f .kamal/secrets && echo 'yes' || echo 'no')"
          if [ -f .kamal/secrets ]; then
            echo "Secrets file size: $(wc -c < .kamal/secrets) bytes"
            echo "Secrets file content (masked): RAILS_MASTER_KEY=[REDACTED]"
          fi
          
          echo "=== Kamal config validation ==="
          bin/kamal config || echo "Kamal config validation failed"
          
          echo "=== Kamal secrets print test ==="
          bin/kamal secrets print || echo "Kamal secrets print failed"

      # Kamalを使って本番環境にデプロイ実行
      - name: Setup Kamal (if needed)
        run: |
          echo "=== Checking if Kamal setup is needed ==="
          if ! bin/kamal app details 2>/dev/null; then
            echo "Running initial Kamal setup..."
            bin/kamal setup
          else
            echo "Kamal already set up, proceeding with deploy"
          fi
        continue-on-error: true

      - name: Deploy with Kamal
        run: bin/kamal deploy
