name: Deploy

on:
  push:
    # branches:
    #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      # リポジトリのソースコードを取得
      - name: Checkout code
        uses: actions/checkout@v4

      # RubyとBundlerをセットアップし、依存関係をキャッシュ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Docker Buildxをセットアップしてビルドキャッシュを有効化
      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      # GitHubランタイム情報をExposeしてDockerキャッシュを最適化
      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      # AWSの認証情報を設定（ECRやEC2にアクセスするため）
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # EC2へのSSH接続を有効化（Kamalがデプロイできるように）
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # デバッグ: 環境変数とKamal設定の確認
      - name: Debug Kamal configuration
        run: |
          echo "=== Environment check ==="
          echo "RAILS_MASTER_KEY is set: ${RAILS_MASTER_KEY:+yes}"
          echo "RAILS_MASTER_KEY length: ${#RAILS_MASTER_KEY}"
          
          echo "=== Kamal config validation ==="
          bin/kamal config || echo "Kamal config validation failed"
          
          echo "=== Kamal secrets validation ==="
          bin/kamal secrets || echo "Kamal secrets validation failed"

      # Kamalを使って本番環境にデプロイ実行
      - name: Deploy with Kamal
        run: bin/kamal deploy
