name: Deploy

on:
  push:
    # branches:
    #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production

    steps:
      # リポジトリのソースコードを取得
      - name: Checkout code
        uses: actions/checkout@v4

      # RubyとBundlerをセットアップし、依存関係をキャッシュ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Docker Buildxをセットアップしてビルドキャッシュを有効化
      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      # GitHubランタイム情報をExposeしてDockerキャッシュを最適化
      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      # AWSの認証情報を設定（ECRやEC2にアクセスするため）
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # EC2へのSSH接続を有効化（Kamalがデプロイできるように）
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # ECRにログイン（Docker認証用）
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ECRログインの詳細確認
      - name: Verify ECR login details
        run: |
          echo "=== AWS Identity ==="
          aws sts get-caller-identity
          echo "=== ECR Repositories ==="
          aws ecr describe-repositories --region ap-northeast-1 || echo "No repositories or access denied"
          echo "=== ECR Repository Check ==="
          aws ecr describe-repositories --repository-names onigiri-recipe --region ap-northeast-1 || echo "onigiri-recipe repository not found"
          echo "=== Docker Config Check (full) ==="
          cat ~/.docker/config.json || echo "No Docker config file found"
          echo "=== Docker Config Check (auths only) ==="
          cat ~/.docker/config.json | jq '.auths' || echo "No Docker auth found"
          echo "=== Manual ECR Login Test ==="
          aws ecr get-login-password --region ap-northeast-1 | docker login --username aws --password-stdin 733853434519.dkr.ecr.ap-northeast-1.amazonaws.com
          echo "=== Docker Config After Manual Login ==="
          cat ~/.docker/config.json | jq '.auths' || echo "Still no Docker auth found"

      # ECRパスワードを環境変数として設定（Kamal用）
      - name: Set KAMAL_REGISTRY_PASSWORD
        run: echo "KAMAL_REGISTRY_PASSWORD=$(aws ecr get-login-password --region ap-northeast-1)" >> $GITHUB_ENV

      # Kamal設定の確認とDocker認証テスト
      - name: Verify Kamal configuration and Docker auth
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          echo "=== ECR Password Length Check ==="
          echo "Password length: ${#KAMAL_REGISTRY_PASSWORD}"
          echo "=== Kamal Full Configuration ==="
          bin/kamal config || echo "Kamal config failed"
          echo "=== Look for registry/repository in config ==="
          bin/kamal config | grep -i -E "(registry|repository|server)" || echo "No registry config found"
          echo "=== Docker Auth After All Setup ==="
          cat ~/.docker/config.json | jq '.' || echo "No Docker config found"
          echo "=== Test Docker Push Auth ==="
          echo "FROM alpine:latest" | docker build -t test-push -
          docker tag test-push 733853434519.dkr.ecr.ap-northeast-1.amazonaws.com/onigiri-recipe:test || echo "Tag failed"
          docker push 733853434519.dkr.ecr.ap-northeast-1.amazonaws.com/onigiri-recipe:test || echo "Push failed - auth issue"

      - name: Deploy with Kamal
        id: kamal-deploy
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bin/kamal deploy
