name: Deploy

on:
  push:
    # branches:
    #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production

    steps:
      # リポジトリのソースコードを取得
      - name: Checkout code
        uses: actions/checkout@v4

      # RubyとBundlerをセットアップし、依存関係をキャッシュ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Docker Buildxをセットアップしてビルドキャッシュを有効化
      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      # GitHubランタイム情報をExposeしてDockerキャッシュを最適化
      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      # AWSの認証情報を設定（ECRやEC2にアクセスするため）
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # EC2へのSSH接続を有効化（Kamalがデプロイできるように）
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # ECRにログイン（Docker認証用）
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ECRリポジトリの存在確認と作成
      - name: Ensure ECR repository exists
        run: |
          if ! aws ecr describe-repositories --repository-names onigiri-recipe --region ap-northeast-1 2>/dev/null; then
            echo "Creating ECR repository: onigiri-recipe"
            aws ecr create-repository --repository-name onigiri-recipe --region ap-northeast-1
            echo "ECR repository created successfully"
          else
            echo "ECR repository onigiri-recipe already exists"
          fi

      # 環境変数の確認
      - name: Debug environment variables and Kamal config
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        run: |
          echo "=== Environment Variables ==="
          echo "DATABASE_USERNAME: ${DATABASE_USERNAME:-'(not set)'}"
          echo "DATABASE_PASSWORD: ${DATABASE_PASSWORD:-'(not set)'}" | sed 's/./*/g'
          echo "DATABASE_HOST: ${DATABASE_HOST:-'(not set)'}"
          echo "=== Deploy.yml env section ==="
          grep -A 10 -B 2 "^env:" config/deploy.yml || echo "env section not found"
          echo "=== Secrets-common content ==="
          cat .kamal/secrets-common
          echo "=== Kamal Configuration with env ==="
          bin/kamal config | grep -A 20 -B 5 -i env || echo "No env configuration found"
          echo "=== Full Kamal Config ==="
          bin/kamal config

      - name: Deploy with Kamal
        id: kamal-deploy
        env:
          RAILS_ENV: production
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          KAMAL_REGISTRY_PASSWORD: ${{ steps.login-ecr.outputs.docker_password_733853434519_dkr_ecr_ap_northeast_1_amazonaws_com }}
        run: bin/kamal deploy
