name: Deploy

on:
  push:
    # branches:
    #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production

    steps:
      # リポジトリのソースコードを取得
      - name: Checkout code
        uses: actions/checkout@v4

      # RubyとBundlerをセットアップし、依存関係をキャッシュ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Docker Buildxをセットアップしてビルドキャッシュを有効化
      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      # GitHubランタイム情報をExposeしてDockerキャッシュを最適化
      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      # AWSの認証情報を設定（ECRやEC2にアクセスするため）
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # EC2へのSSH接続を有効化（Kamalがデプロイできるように）
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # ECRにログイン（Docker認証用）
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ECRリポジトリの存在確認と作成
      - name: Ensure ECR repository exists
        run: |
          if ! aws ecr describe-repositories --repository-names onigiri-recipe --region ap-northeast-1 2>/dev/null; then
            echo "Creating ECR repository: onigiri-recipe"
            aws ecr create-repository --repository-name onigiri-recipe --region ap-northeast-1
            echo "ECR repository created successfully"
          else
            echo "ECR repository onigiri-recipe already exists"
          fi

      # ECRパスワードを環境変数として設定（Kamal用）
      - name: Set KAMAL_REGISTRY_PASSWORD
        run: |
          ECR_PASSWORD=$(aws ecr get-login-password --region ap-northeast-1)
          echo "KAMAL_REGISTRY_PASSWORD=${ECR_PASSWORD}" >> $GITHUB_ENV
          echo "ECR password set (length: ${#ECR_PASSWORD})"

      # Docker認証状況の確認
      - name: Verify Docker authentication
        run: |
          echo "=== Verify ECR authentication ==="
          docker system info | grep -A 10 "Registry Mirrors" || echo "No registry info"
          echo "=== Test ECR connection ==="
          echo "FROM alpine:latest" > Dockerfile.test
          docker build -f Dockerfile.test -t 733853434519.dkr.ecr.ap-northeast-1.amazonaws.com/onigiri-recipe:test .
          docker push 733853434519.dkr.ecr.ap-northeast-1.amazonaws.com/onigiri-recipe:test
          echo "=== ECR connection successful ==="
          rm -f Dockerfile.test

      - name: Deploy with Kamal
        id: kamal-deploy
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bin/kamal deploy
